@startuml ci
skinparam monochrome true
skinparam handwritten true

start

:编写IDL;
:Github Action;
split
  :**Java**
  - ProtoBuf types
  - gRPC server
  - gRPC client;
  :Maven Registry;
split again
  :**Node**  
  - ProtoBuf types
  - gRPC server
  - gRPC client;
  :NPM Registry;
split again
  :**Go**
  - ProtoBuf types
  - HTTP client
  - API mock
  - grpc-gateway server
  - gRPC server
  - gRPC client;
  :Github Repository;
end split

stop

@enduml